---
title: "SSS"
author: "Jens Daniel Müller & Lara Burchardt"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r library, message=FALSE, warning=FALSE, echo= FALSE}

library(tidyverse)
library(ncdf4)
library(vroom)
library(lubridate)
library(geosphere)
library(dygraphs)
library(xts)
library(here)
library(metR)

```

```{r subsetting_criteria, echo=FALSE}

# route
select_route <- "E"

# variable names
var <- "SSS_east" #sea surface salinity, route e
```
# Medium Salinity 

In the following section, we want to calculate the medium salinity per month and transect section. We will therefore end up with 544 x 12 salinity values.

```{r medium_salinity, eval = FALSE}

nc <- nc_open(paste("data/Finnmaid/", "FM_all_2019_on_standard_tracks.nc", sep = ""))

# read required vectors from netcdf file
route <- ncvar_get(nc, "route")
route <- unlist(strsplit(route, ""))
date_time <- ncvar_get(nc, "time")
latitude_east <- ncvar_get(nc, "latitude_east")
longitude_east <-ncvar_get(nc, "longitude_east")
date_time_o <- ncvar_get(nc, "otime_east")

  array <- ncvar_get(nc, var) # store the data in a 2-dimensional array
  #dim(array) # should have 2 dimensions: 544 coordinate, 2089 time steps
  
  fillvalue <- ncatt_get(nc, var, "_FillValue")
  array[array == fillvalue$value] <- NA
  rm(fillvalue)
  
  cor_vector <- c(1:544)
  
  for (i in seq(1,length(route),1)){
  
      
    if(route[i] == select_route) {
      slice <- array[i,]          #define slice of the data, per row (per measurment day)
      value <- slice
      date <- ymd("2000-01-01") + date_time[i]
      
      #if detailed date/time information is needed: uncomment that
      #date <- as.Date(c(1:544))   # set up "date" variable to be overwritten later, needs to be "Date" object
      #for (a in seq(1,length(latitude_east),1)){              # for slice i the corresponding 544 transect steps are  
      #temp_time <- ymd("2000-01-01") + date_time_o[i,a]       # adjoined by corresponding time ("otime_east")
      #date[a] <- temp_time
      #}
      #temp <- bind_cols(value = value, lon = longitude_east, lat = latitude_east, 
      #corvector =   cor_vector, date_time = date)
      #temp$date_time <- as.POSIXct(temp$date_time)
      
      #when detailed time/date information is needed, comment the following
      temp <- bind_cols(value = value, lon = longitude_east, lat = latitude_east,
      corvector =  cor_vector)
      temp$date <- date
      # 
      
      if (exists("fm_sss", inherits = FALSE)){
        fm_sss <- bind_rows(fm_sss, temp)
      } else{fm_sss <- temp}
      
      rm(temp, value, date)
    }
    print(i)
  }

nc_close(nc)

fm_sss_corvector <- fm_sss %>% 
  transmute(sss = value,
         year = year(date),
         month = month(date),
         corvector = corvector )

  for (cor in 1:544){
    
    temp <- fm_sss_corvector %>% 
      filter(corvector == cor) %>% 
      select(month, corvector, sss) %>% 
      group_by(month, corvector) %>% 
      summarise_all(mean, na.rm = TRUE)
    
    if (exists("fm_sss_monthly", inherits = FALSE)){
        fm_sss_monthly <- bind_rows(fm_sss_monthly, temp)
      } else{fm_sss_monthly <- temp}
    rm(temp)
  }
  

fm_sss_monthly %>% 
vroom_write(here::here("data/_summarized_data_files/", file = "fm_sss_monthly_perTransect.csv"))


rm(fm_sss_monthly,  fm_sss_corvector, var, select_route)
```

```{r scatterplot_salinity}

fm_sss_monthly <- vroom::vroom(
  here::here("data/_summarized_data_files","fm_sss_monthly_perTransect.csv"))

fm_sss_monthly <- fm_sss_monthly %>% 
  mutate(dist.trav = corvector * 2,
         month_factor = as.factor(month))

fm_sss_monthly %>% 
  ggplot(aes(dist.trav, sss, color = month_factor))+
  geom_point(size = 0.1)+
  labs(x="Distance to Travemuende [km]",
       y="Surface Salinity")+
  theme_bw()+
  scale_colour_brewer(palette = "Paired",
                      type = "qual",
                      name = "Month",
                      labels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))

rm(fm_sss_monthly)
```
